version: '2'

volumes:
  registry: {}
  certificates: {}
  postgres_data: {}

services:
  postgres:
    image: postgres:9.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
      - POSTGRES_DB=tinyauth

  tinyauth:
    image: tinyauth/tinyauth:dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
    ports:
      - 8000:8000

  registry:
    image: registry:2
    volumes:
    - registry:/var/lib/registry
    - certificates:/certificates
    environment:
    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://localhost/auth/v2/token
    - REGISTRY_AUTH_TOKEN_SERVICE=docker-registry
    - REGISTRY_AUTH_TOKEN_ISSUER=tinyauth
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certificates/server.pem
    - REGISTRY_HTTP_ADDR=0.0.0.0:5000

  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile-dev
    volumes:
      - certificates:/certificates
      - .:/app/src

  nginx:
    build:
      context: docker/nginx
    ports:
      - "443:443"
      - "80:80"
