version: '2'

volumes:
  registry: {}
  certificates: {}
  postgres_data: {}

services:
  postgres:
    image: postgres:9.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
      - POSTGRES_DB=tinyauth

  tinyauth:
    image: tinyauth/tinyauth:dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
    ports:
      - 8000:8000

  registry:
    build:
      context: docker/registry
    volumes:
      - registry:/registry
      - certificates:/certificates

  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    volumes:
      - certificates:/certificates

  nginx:
    build:
      context: docker/nginx
    ports:
      - "443:443"
      - "80:80"
